// Code generated by gometagen; DO NOT EDIT.
// Hash point: /tmp/claude-agent-tmp/gometagen-example-content-source/assets
// Generated at: 2026-05-26T18:05:00Z
package with_content_hash

const (
	Name       string = "example-content"
	DateUpdate string = "05-26-2026"
	Hash       string = "0b5bda523a1ee88cb49bc83a9cffbabfa625c3fc"

	Version      string = "release.9.3-alpha.2"
	VersionMajor string = "release"
	VersionMinor uint16 = 9
	VersionPatch uint16 = 3
)
