// Code generated by gometagen; DO NOT EDIT.
// Hash point: /tmp/claude-agent-tmp/gometagen-example-git-source
// Generated at: 2026-05-26T18:00:00Z
package with_git_hash

const (
	Name       string = "example-git"
	DateUpdate string = "05-26-2026"
	Hash       string = "768c785488b6fec00c0a4e8e6e34e0612e0cba71"

	Version      string = "v2.7.4"
	VersionMajor string = "v2"
	VersionMinor uint16 = 7
	VersionPatch uint16 = 4
)
